image: python:3.7-slim

pages:
  stage: deploy
  script:
  - apt-get update && apt-get  install -y ca-certificates musl-dev  g++ python3 python3-dev  curl tar gzip bash wget
  - pip install --upgrade pip
  - pip install pyzmq
  - pip install sphinx  nbsphinx numpydoc sphinx_automodapi pypandoc sphinx-autopackagesummary pandas scipy
  - wget https://github.com/jgm/pandoc/releases/download/2.11.0.2/pandoc-2.11.0.2-linux-amd64.tar.gz 
  - tar -xvzf pandoc-2.11.0.2-linux-amd64.tar.gz --strip-components 1 -C /usr/local/
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - opensource
