#!/bin/bash
# from https://hub.docker.com/r/nvidia/cuda/

docker_dir=$(readlink -f $0 | xargs dirname)
basename="$(dirname "$docker_dir")"
echo $basename



docker build --file 'Dockerfile' . -t docker_energym_base


docker run -it --name docker_energym_base \
	-p 8106:8106 \
	--volume $basename/:/home/energym \
docker_energym_base
